-- [nfnl] plugin/configs/lspconfig.fnl
local lsp_zero = require("lsp-zero")
local function _1_(client, bufnr)
  return lsp_zero.default_keymaps({buffer = bufnr})
end
lsp_zero.on_attach(_1_)
lsp_zero.format_on_save({servers = {rust_analyzer = {"rust"}, biome = {"typescript", "javascript"}, vue_ls = {"vue"}}})
lsp_zero.set_sign_icons({error = "\226\156\152", warn = "\226\150\178", hint = "\226\154\145", info = "\194\187"})
local neodev = require("neodev")
neodev.setup()
local mason = require("mason")
mason.setup({registries = {"github:mason-org/mason-registry", "github:Crashdummyy/mason-registry"}})
local mason_lspconfig = require("mason-lspconfig")
mason_lspconfig.setup({handlers = {lsp_zero.default_setup}, ensure_installed = {"ts_ls", "rust_analyzer", "bashls", "clangd", "clojure_lsp", "dockerls", "eslint", "elmls", "millet", "fsautocomplete", "gopls", "html", "biome", "lua_ls", "autotools_ls", "marksman", "glsl_analyzer", "powershell_es", "jedi_language_server", "sqlls", "vue_ls", "wgsl_analyzer", "yamlls", "zls"}})
local mason_tool_installer = require("mason-tool-installer")
mason_tool_installer.setup({ensure_installed = {"prettier", "prettierd"}})
local cmp = require("cmp")
cmp.setup({mapping = cmp.mapping.preset.insert({["<C-Space>"] = cmp.mapping.complete({select = true}), ["<C-enter>"] = cmp.mapping.confirm({select = true})}), preselect = "item", completion = {completeopt = "menu,menuone,noinsert"}, sources = {{name = "nvim_lsp"}, {name = "nvim_lua"}, {name = "conjure"}, {name = "supermaven"}, {name = "minuet"}}, window = {completion = cmp.config.window.bordered(), documentation = cmp.config.window.bordered()}})
local function _2_()
  return cmp.setup.buffer({sources = {{name = "nvim_lsp"}, {name = "nvim_lua"}, {name = "conjure"}}})
end
vim.api.nvim_create_autocmd("FileType", {pattern = {"norg", "markdown", "org", "text", "gitcommit"}, callback = _2_})
local lspconfig = require("lspconfig")
return lspconfig.racket_langserver.setup({})
