name: Compile and Deploy Lua Files

on:
  push:
    branches:
      - main

jobs:
  deploy-lua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 luarocks liblua5.3-dev

      - name: Install Fennel
        run: |
          sudo luarocks install fennel

      - name: Make Lua files
        run: make

      - name: Checkout torsi branch
        uses: actions/checkout@v3
        with:
          ref: 'torsi'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          path: 'temp_branch'

      - name: Clear old Lua files in torsi branch
        run: |
          cd temp_branch
          git rm -r *.lua || echo "No Lua files to remove"
          git clean -fdx

      - name: Copy Lua files from main branch while preserving directory structure
        run: |
          rsync -av --exclude='temp_branch/' --include='*/' --include='*.lua' --exclude='*' ./ temp_branch/

      - name: Commit Lua files
        working-directory: temp_branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Lua files - ${{ github.sha }}" || echo "No changes to commit"
          git push origin torsi --force

